# Generated by Django 4.1.7 on 2023-03-12 15:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.CharField(max_length=100)),
                ('profile_image', models.CharField(max_length=1000)),
                ('facebook_url', models.CharField(max_length=1000)),
                ('twitter_url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.IntegerField(default=1)),
                ('distance', models.IntegerField(default=1)),
                ('group_size', models.IntegerField(default=1)),
                ('trail', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('mountain', models.CharField(max_length=100)),
                ('altitude', models.IntegerField(default=1)),
                ('area', models.IntegerField(default=1)),
                ('cost', models.IntegerField(default=1)),
                ('level', models.CharField(choices=[('Difficult', 'Difficult'), ('Easy', 'Easy'), ('Moderate', 'Moderate')], default='Easy', max_length=100)),
                ('hike_date', models.DateField()),
                ('image_url', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledHikers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
