# Generated by Django 4.1.7 on 2023-03-13 03:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_enrolledhikers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='image_url',
        ),
        migrations.AddField(
            model_name='hike',
            name='gmap_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guide',
            name='profile_image',
            field=models.CharField(max_length=10000),
        ),
    ]
