# Generated by Django 4.1.7 on 2023-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_hike_image_url_hike_gmap_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='level',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], default='High', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='enrolledhikers',
            unique_together={('user', 'hike')},
        ),
    ]
