# Generated by Django 4.1.7 on 2023-03-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hike_available_capcity'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Guide/'),
        ),
        migrations.AddField(
            model_name='hike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Hikes/'),
        ),
        migrations.AddField(
            model_name='hike',
            name='image_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='profile_image',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
