# Generated by Django 4.1.7 on 2023-03-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="forget_password_token",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
