# Generated by Django 4.1.7 on 2023-03-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customer_forget_password_token'),
        ('main', '0010_alter_contact_description'),
    ]

    operations = [
    ]
