# Generated by Django 4.1.7 on 2023-03-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20230326_1250'),
        ('main', '0011_merge_20230326_1806'),
    ]

    operations = [
    ]
